[pytest]
testpaths = tests
pythonpath = .
python_files = test_*.py
python_functions = test_*
addopts =
   --rootdir=.
   -v
   -rA
   -s
norecursedirs = .venv .git
markers =
    # уровень важности
    critical: Критичные
    high: Высокий приоритет
    medium: Средний приоритет
    low: Низкий приоритет
    
    # тип
    positive: Позитивные сценарии
    negative: Негативные сценарии

    # покрытие
    scenario: полноценные сценарии взаимодействия
    endpoint: взаимодействие с конкретными endpoints
